### Exercise 1.02: Indexing, Slicing, Splitting, and Iterating

In [1]:
import numpy as np

In [2]:
dataset = np.genfromtxt('../Datasets/normal_distribution_splittable.csv', delimiter=',')

In [3]:
second_row = dataset[1]
np.mean(second_row)

96.90038836444445

In [4]:
last_row = dataset[-1]
np.mean(last_row)

100.18096645222221

In [5]:
np.mean(dataset)

100.11276252319443

In [6]:
# access the first value of the first row and the last value of the second last row
first_val_first_row = dataset[0][0]
np.mean(first_val_first_row)

99.14931546

In [7]:
first_val_first_row

99.14931546

In [8]:
last_val_second_last_row = dataset[-2, -1]
np.mean(last_val_second_last_row)

101.2226037

In [9]:
last_val_second_last_row

101.2226037

In [10]:
"""
slicing an intersection of 4 elements (2x2) of the first two rows
and the first two columns
"""
subsection_2x2 = dataset[1:3, 1:3]

In [11]:
np.mean(subsection_2x2)

95.63393608250001

In [12]:
# we want to have every other element of the fifth row
every_other_elem = dataset[4, ::2]
np.mean(every_other_elem)

98.35235805800001

In [13]:
# reverse the elements in a slice using negative numbers:
reversed_last_row = dataset[-1, ::-1]
np.mean(reversed_last_row)

100.18096645222222

In [17]:
hor_splits = np.hsplit(dataset,(3))
hor_splits[0].shape

(24, 3)

In [18]:
# split the first third into two equal parts vertically
ver_splits = np.vsplit(hor_splits[0],(2))
ver_splits

[array([[ 99.14931546, 104.03852715, 107.43534677],
        [ 92.02628776,  97.10439252,  99.32066924],
        [ 95.66253664,  95.17750125,  90.93318132],
        [ 91.37294597, 100.96781394, 100.40118279],
        [101.20862522, 103.5730309 , 100.28690912],
        [102.80387079,  98.29687616,  93.24376389],
        [106.71751618, 102.97585605,  98.45723272],
        [ 96.02548256, 102.82360856, 106.47551845],
        [105.30350449,  92.87730812, 103.19258339],
        [110.44484313,  93.87155456, 101.5363647 ],
        [101.3514185 , 100.37372248, 106.6471081 ],
        [ 97.21315663, 107.02874163, 102.17642112]]),
 array([[ 95.65982034, 107.22482426, 107.19119932],
        [100.39303522,  92.0108226 ,  97.75887636],
        [103.1521596 , 109.40523174,  93.83969256],
        [106.11454989,  88.80221141,  94.5081787 ],
        [ 96.78266211,  99.84251605, 104.03478031],
        [101.86186193, 103.61720152,  99.57859892],
        [ 97.49594839,  96.59385486, 104.63817694],
        [ 96.76814836,  91.6779221 , 101.79132774],
        [106.89005002, 106.57364584, 102.26648279],
        [ 99.80873105, 101.63973121, 106.46476468],
        [ 96.10020311,  94.57421727, 100.80409326],
        [ 94.11176915,  99.62387832, 104.51786419]])]

In [19]:
print("Dataset", dataset.shape)
print("Subset", ver_splits[0].shape)

Dataset (24, 9)
Subset (12, 3)

In [20]:
# iterate over the whole dataset
curr_index = 0
for x in np.nditer(dataset):
    print(x, curr_index)
    curr_index += 1

99.14931546 0
104.03852715 1
107.43534677 2
97.85230675 3
98.74986914 4
98.80833412 5
96.81964892 6
98.56783189 7
101.34745901 8
92.02628776 9
97.10439252 10
99.32066924 11
97.24584816 12
92.9267508 13
92.65657752 14
105.7197853 15
101.23162942 16
93.87155456 17
95.66253664 18
95.17750125 19
90.93318132 20
110.18889465 21
98.80084371 22
105.95297652 23
98.37481387 24
106.54654286 25
107.22482426 26
91.37294597 27
100.96781394 28
100.40118279 29
113.42090475 30
105.48508838 31
91.6604946 32
106.1472841 33
95.08715803 34
103.40412146 35
101.20862522 36
103.5730309 37
100.28690912 38
105.85269352 39
93.37126331 40
108.57980357 41
100.79478953 42
94.20019732 43
96.10020311 44
102.80387079 45
98.29687616 46
93.24376389 47
97.24130034 48
89.03452725 49
96.2832753 50
104.60344836 51
101.13442416 52
97.62787811 53
106.71751618 54
102.97585605 55
98.45723272 56
100.72418901 57
106.39798503 58
95.46493436 59
94.35373179 60
106.83273763 61
100.07721494 62
96.02548256 63
102.82360856 64
106.47551845 65
101.34745901 66
102.45651798 67
98.74767493 68
97.57544275 69
92.5748759 70
91.37294597 71
105.30350449 72
92.87730812 73
103.19258339 74
104.40518318 75
101.29326772 76
100.85447132 77
101.2226037 78
106.03868807 79
97.85230675 80
110.44484313 81
93.87155456 82
101.5363647 83
97.65393524 84
92.75048583 85
101.72074646 86
96.96851209 87
103.29147111 88
99.14931546 89
101.3514185 90
100.37372248 91
106.6471081 92
100.61742813 93
105.0320535 94
99.35999981 95
98.87007532 96
95.85284217 97
93.97853495 98
97.21315663 99
107.02874163 100
102.17642112 101
96.74630281 102
95.93799169 103
102.62384733 104
105.07475277 105
97.59572169 106
106.57364584 107
95.65982034 108
107.22482426 109
107.19119932 110
102.93039474 111
85.98839623 112
95.19184343 113
91.32093303 114
102.35313953 115
100.39303522 116
100.39303522 117
92.0108226 118
97.75887636 119
93.18884302 120
100.44940274 121
108.09423367 122
96.50342927 123
99.58664719 124
95.19184343 125
103.1521596 126
109.40523174 127
93.83969256 128
99.95827854 129
101.83462816 130
99.69982772 131
103.05289628 132
103.93383957 133
104.15899829 134
106.11454989 135
88.80221141 136
94.5081787 137
94.59300658 138
101.08830521 139
96.34622848 140
96.89244283 141
98.07122664 142
100.28690912 143
96.78266211 144
99.84251605 145
104.03478031 146
106.57052697 147
105.13668343 148
105.37011896 149
99.07551254 150
104.15899829 151
98.75108352 152
101.86186193 153
103.61720152 154
99.57859892 155
99.4889538 156
103.05541444 157
98.65912661 158
98.72774132 159
104.70526438 160
110.44484313 161
97.49594839 162
96.59385486 163
104.63817694 164
102.55198606 165
105.86078488 166
96.5937781 167
93.04610867 168
99.92159953 169
100.96781394 170
96.76814836 171
91.6779221 172
101.79132774 173
101.20773355 174
98.29243952 175
101.83845792 176
97.94046856 177
102.20618501 178
91.37294597 179
106.89005002 180
106.57364584 181
102.26648279 182
107.40064604 183
99.94318168 184
103.40412146 185
106.38276709 186
98.00253006 187
97.10439252 188
99.80873105 189
101.63973121 190
106.46476468 191
110.43976681 192
100.69156231 193
99.99579473 194
101.32113654 195
94.76253572 196
97.24130034 197
96.10020311 198
94.57421727 199
100.80409326 200
105.02389857 201
98.61325194 202
95.62359311 203
97.99762409 204
103.83852459 205
101.2226037 206
94.11176915 207
99.62387832 208
104.51786419 209
97.62787811 210
93.97853495 211
98.75108352 212
106.05042487 213
100.07721494 214
106.89005002 215

In [21]:
for index, value in np.ndenumerate(dataset):
    print(index, value)

(0, 0) 99.14931546
(0, 1) 104.03852715
(0, 2) 107.43534677
(0, 3) 97.85230675
(0, 4) 98.74986914
(0, 5) 98.80833412
(0, 6) 96.81964892
(0, 7) 98.56783189
(0, 8) 101.34745901
(1, 0) 92.02628776
(1, 1) 97.10439252
(1, 2) 99.32066924
(1, 3) 97.24584816
(1, 4) 92.9267508
(1, 5) 92.65657752
(1, 6) 105.7197853
(1, 7) 101.23162942
(1, 8) 93.87155456
(2, 0) 95.66253664
(2, 1) 95.17750125
(2, 2) 90.93318132
(2, 3) 110.18889465
(2, 4) 98.80084371
(2, 5) 105.95297652
(2, 6) 98.37481387
(2, 7) 106.54654286
(2, 8) 107.22482426
(3, 0) 91.37294597
(3, 1) 100.96781394
(3, 2) 100.40118279
(3, 3) 113.42090475
(3, 4) 105.48508838
(3, 5) 91.6604946
(3, 6) 106.1472841
(3, 7) 95.08715803
(3, 8) 103.40412146
(4, 0) 101.20862522
(4, 1) 103.5730309
(4, 2) 100.28690912
(4, 3) 105.85269352
(4, 4) 93.37126331
(4, 5) 108.57980357
(4, 6) 100.79478953
(4, 7) 94.20019732
(4, 8) 96.10020311
(5, 0) 102.80387079
(5, 1) 98.29687616
(5, 2) 93.24376389
(5, 3) 97.24130034
(5, 4) 89.03452725
(5, 5) 96.2832753
(5, 6) 104.60344836
(5, 7) 101.13442416
(5, 8) 97.62787811
(6, 0) 106.71751618
(6, 1) 102.97585605
(6, 2) 98.45723272
(6, 3) 100.72418901
(6, 4) 106.39798503
(6, 5) 95.46493436
(6, 6) 94.35373179
(6, 7) 106.83273763
(6, 8) 100.07721494
(7, 0) 96.02548256
(7, 1) 102.82360856
(7, 2) 106.47551845
(7, 3) 101.34745901
(7, 4) 102.45651798
(7, 5) 98.74767493
(7, 6) 97.57544275
(7, 7) 92.5748759
(7, 8) 91.37294597
(8, 0) 105.30350449
(8, 1) 92.87730812
(8, 2) 103.19258339
(8, 3) 104.40518318
(8, 4) 101.29326772
(8, 5) 100.85447132
(8, 6) 101.2226037
(8, 7) 106.03868807
(8, 8) 97.85230675
(9, 0) 110.44484313
(9, 1) 93.87155456
(9, 2) 101.5363647
(9, 3) 97.65393524
(9, 4) 92.75048583
(9, 5) 101.72074646
(9, 6) 96.96851209
(9, 7) 103.29147111
(9, 8) 99.14931546
(10, 0) 101.3514185
(10, 1) 100.37372248
(10, 2) 106.6471081
(10, 3) 100.61742813
(10, 4) 105.0320535
(10, 5) 99.35999981
(10, 6) 98.87007532
(10, 7) 95.85284217
(10, 8) 93.97853495
(11, 0) 97.21315663
(11, 1) 107.02874163
(11, 2) 102.17642112
(11, 3) 96.74630281
(11, 4) 95.93799169
(11, 5) 102.62384733
(11, 6) 105.07475277
(11, 7) 97.59572169
(11, 8) 106.57364584
(12, 0) 95.65982034
(12, 1) 107.22482426
(12, 2) 107.19119932
(12, 3) 102.93039474
(12, 4) 85.98839623
(12, 5) 95.19184343
(12, 6) 91.32093303
(12, 7) 102.35313953
(12, 8) 100.39303522
(13, 0) 100.39303522
(13, 1) 92.0108226
(13, 2) 97.75887636
(13, 3) 93.18884302
(13, 4) 100.44940274
(13, 5) 108.09423367
(13, 6) 96.50342927
(13, 7) 99.58664719
(13, 8) 95.19184343
(14, 0) 103.1521596
(14, 1) 109.40523174
(14, 2) 93.83969256
(14, 3) 99.95827854
(14, 4) 101.83462816
(14, 5) 99.69982772
(14, 6) 103.05289628
(14, 7) 103.93383957
(14, 8) 104.15899829
(15, 0) 106.11454989
(15, 1) 88.80221141
(15, 2) 94.5081787
(15, 3) 94.59300658
(15, 4) 101.08830521
(15, 5) 96.34622848
(15, 6) 96.89244283
(15, 7) 98.07122664
(15, 8) 100.28690912
(16, 0) 96.78266211
(16, 1) 99.84251605
(16, 2) 104.03478031
(16, 3) 106.57052697
(16, 4) 105.13668343
(16, 5) 105.37011896
(16, 6) 99.07551254
(16, 7) 104.15899829
(16, 8) 98.75108352
(17, 0) 101.86186193
(17, 1) 103.61720152
(17, 2) 99.57859892
(17, 3) 99.4889538
(17, 4) 103.05541444
(17, 5) 98.65912661
(17, 6) 98.72774132
(17, 7) 104.70526438
(17, 8) 110.44484313
(18, 0) 97.49594839
(18, 1) 96.59385486
(18, 2) 104.63817694
(18, 3) 102.55198606
(18, 4) 105.86078488
(18, 5) 96.5937781
(18, 6) 93.04610867
(18, 7) 99.92159953
(18, 8) 100.96781394
(19, 0) 96.76814836
(19, 1) 91.6779221
(19, 2) 101.79132774
(19, 3) 101.20773355
(19, 4) 98.29243952
(19, 5) 101.83845792
(19, 6) 97.94046856
(19, 7) 102.20618501
(19, 8) 91.37294597
(20, 0) 106.89005002
(20, 1) 106.57364584
(20, 2) 102.26648279
(20, 3) 107.40064604
(20, 4) 99.94318168
(20, 5) 103.40412146
(20, 6) 106.38276709
(20, 7) 98.00253006
(20, 8) 97.10439252
(21, 0) 99.80873105
(21, 1) 101.63973121
(21, 2) 106.46476468
(21, 3) 110.43976681
(21, 4) 100.69156231
(21, 5) 99.99579473
(21, 6) 101.32113654
(21, 7) 94.76253572
(21, 8) 97.24130034
(22, 0) 96.10020311
(22, 1) 94.57421727
(22, 2) 100.80409326
(22, 3) 105.02389857
(22, 4) 98.61325194
(22, 5) 95.62359311
(22, 6) 97.99762409
(22, 7) 103.83852459
(22, 8) 101.2226037
(23, 0) 94.11176915
(23, 1) 99.62387832
(23, 2) 104.51786419
(23, 3) 97.62787811
(23, 4) 93.97853495
(23, 5) 98.75108352
(23, 6) 106.05042487
(23, 7) 100.07721494
(23, 8) 106.89005002

In [22]:
# (5, 6) 104.60344836
dataset[5,6]

104.60344836

In [23]:
# create a dataset that fits the data
import pandas as pd
df = pd.DataFrame(np.random.randint(0, 100, size=(24, 24)), columns=list('ABCDEFGHIJKLMNOPQRSTWXYZ'))

In [25]:
df[df.A > 50]

,A,B,C,D,E,F,G,H,I,J,...,O,P,Q,R,S,T,W,X,Y,Z
0,71,66,51,14,43,67,39,75,87,90,...,23,85,3,43,92,44,97,94,21,27
1,83,8,21,23,5,86,58,65,10,5,...,11,74,7,77,21,62,62,31,28,41
3,92,33,19,36,86,97,29,44,94,71,...,3,59,94,73,69,2,44,50,37,50
4,94,55,13,89,68,29,19,23,94,77,...,48,44,48,90,22,72,27,80,68,62
6,51,5,7,97,84,36,84,52,55,38,...,38,76,1,13,53,40,40,51,86,59
8,91,33,46,43,84,38,29,62,79,95,...,68,44,66,20,65,63,23,49,18,14
10,51,74,33,57,55,12,7,39,13,76,...,27,83,8,59,60,34,31,94,45,19
11,66,37,89,68,13,49,66,58,66,93,...,11,64,98,61,81,84,42,51,92,11
12,94,2,14,69,7,87,44,64,22,48,...,26,65,22,12,80,65,35,20,46,68
16,52,63,98,57,24,52,28,65,49,12,...,13,89,1,18,53,48,46,11,18,54
18,85,44,46,9,93,45,42,91,20,9,...,59,63,79,46,80,18,28,99,0,41
22,80,31,74,66,51,16,81,67,14,17,...,19,1,26,73,75,69,92,3,75,23

In [30]:
df[df.A > 50][df.B > 50]

C:\Users\lorra\AppData\Local\Temp\ipykernel_32840\3450859088.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.A > 50][df.B > 50]

,A,B,C,D,E,F,G,H,I,J,...,O,P,Q,R,S,T,W,X,Y,Z
0,71,66,51,14,43,67,39,75,87,90,...,23,85,3,43,92,44,97,94,21,27
4,94,55,13,89,68,29,19,23,94,77,...,48,44,48,90,22,72,27,80,68,62
10,51,74,33,57,55,12,7,39,13,76,...,27,83,8,59,60,34,31,94,45,19
16,52,63,98,57,24,52,28,65,49,12,...,13,89,1,18,53,48,46,11,18,54

In [38]:
df2 = np.extract( (df < 3), df)

In [39]:
df2

array([0, 2, 2, 2, 1, 2, 1, 1, 0, 0, 1, 2, 2, 2, 1, 2])

In [40]:
# values bigger 5 and smaller 10
df[(df > 5) & (df < 10)]

,A,B,C,D,E,F,G,H,I,J,...,O,P,Q,R,S,T,W,X,Y,Z
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.0,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
# indices of values bigger
np.where(df > 5)

(array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
         6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
         9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11,
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12,
        12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15,
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
        15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
        16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17,
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
        17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
        21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23,
        23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23],
       dtype=int64),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17,
        18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  5,  6,  7,  8, 10, 11, 12,
        13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  2,  3,  4,  5,  6,  7,
         8,  9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23,  0,  1,  2,
         3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18, 20, 21,
        22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
        15, 16, 17, 18, 19, 20, 21, 22, 23,  1,  2,  3,  4,  5,  6,  7,  8,
         9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23,  0,  2,  3,
         4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22,
        23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,
         9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  0,  1,
         3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
        14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  0,
         2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
        12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,
         5,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18, 20, 21, 22, 23,  0,
         1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,
         5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
        23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
        10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,  0,  1,  2,
         3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11,
        13, 14, 16, 17, 18, 19, 20, 22, 23,  0,  2,  3,  4,  5,  6,  7,  8,
         9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       dtype=int64))

In [44]:
# values sorted on last axis
np.sort(df)

array([[ 3, 10, 14, 21, 23, 23, 27, 33, 39, 43, 43, 44, 51, 66, 67, 71,
        75, 79, 85, 87, 90, 92, 94, 97],
       [ 5,  5,  7,  8, 10, 11, 21, 21, 23, 24, 28, 31, 41, 56, 58, 62,
        62, 65, 65, 74, 77, 83, 86, 87],
       [ 0,  2,  5,  5, 10, 10, 12, 29, 30, 32, 33, 33, 39, 44, 52, 67,
        68, 68, 72, 73, 74, 87, 89, 94],
       [ 2,  3, 19, 24, 29, 33, 36, 37, 44, 44, 50, 50, 59, 69, 69, 71,
        71, 73, 74, 86, 92, 94, 94, 97],
       [10, 13, 19, 22, 23, 27, 29, 44, 48, 48, 55, 62, 68, 68, 69, 72,
        72, 76, 77, 80, 89, 90, 94, 94],
       [ 2,  3,  9, 20, 23, 25, 31, 32, 37, 37, 37, 46, 51, 51, 57, 60,
        73, 78, 81, 82, 89, 90, 96, 98],
       [ 1,  3,  5,  7, 13, 36, 38, 38, 40, 40, 51, 51, 52, 53, 55, 59,
        71, 76, 79, 84, 84, 86, 97, 98],
       [17, 17, 20, 37, 37, 42, 42, 54, 55, 62, 63, 63, 64, 67, 69, 70,
        70, 71, 74, 80, 86, 91, 95, 99],
       [14, 15, 18, 20, 23, 29, 33, 38, 43, 44, 46, 49, 62, 63, 65, 66,
        68, 79, 84, 88, 91, 95, 98, 98],
       [ 3,  5,  7, 10, 12, 14, 15, 16, 17, 19, 27, 28, 34, 39, 40, 46,
        50, 52, 58, 66, 77, 79, 85, 91],
       [ 7,  8, 12, 13, 19, 21, 27, 31, 33, 34, 39, 40, 45, 51, 51, 55,
        57, 59, 60, 74, 74, 76, 83, 94],
       [ 4, 11, 11, 13, 37, 42, 47, 49, 50, 51, 58, 61, 61, 64, 66, 66,
        66, 68, 81, 84, 89, 92, 93, 98],
       [ 2,  7, 12, 14, 20, 22, 22, 26, 35, 43, 44, 46, 48, 48, 55, 59,
        64, 65, 65, 68, 69, 80, 87, 94],
       [ 8, 13, 17, 19, 24, 25, 29, 31, 31, 31, 35, 38, 42, 47, 49, 53,
        59, 60, 64, 65, 69, 74, 81, 99],
       [ 1,  4,  5, 24, 24, 25, 25, 27, 45, 46, 49, 60, 68, 71, 71, 75,
        82, 83, 87, 87, 91, 93, 94, 95],
       [ 7, 14, 17, 22, 26, 28, 30, 30, 35, 41, 42, 46, 50, 51, 52, 57,
        60, 63, 64, 66, 80, 82, 83, 92],
       [ 1, 11, 12, 13, 18, 18, 24, 28, 33, 46, 48, 49, 52, 52, 53, 54,
        57, 63, 65, 70, 83, 84, 89, 98],
       [ 0,  9, 11, 14, 19, 22, 22, 27, 31, 33, 42, 42, 44, 52, 56, 62,
        69, 74, 82, 83, 86, 89, 90, 92],
       [ 0,  9,  9, 18, 20, 26, 28, 35, 41, 42, 44, 45, 46, 46, 59, 63,
        79, 80, 85, 85, 91, 93, 97, 99],
       [12, 20, 21, 22, 27, 28, 28, 29, 29, 38, 41, 45, 45, 47, 54, 56,
        64, 74, 76, 78, 80, 86, 91, 96],
       [ 1,  6, 13, 13, 17, 18, 20, 30, 33, 33, 36, 36, 42, 43, 43, 48,
        53, 54, 56, 62, 71, 73, 74, 82],
       [ 2,  2,  4,  5,  6,  7, 12, 26, 27, 29, 34, 38, 57, 61, 64, 71,
        72, 72, 75, 78, 86, 92, 92, 99],
       [ 1,  2,  3,  4, 14, 16, 17, 19, 23, 26, 31, 51, 66, 67, 69, 73,
        74, 75, 75, 79, 80, 81, 84, 92],
       [ 2, 11, 11, 13, 26, 30, 34, 36, 37, 42, 54, 56, 56, 58, 68, 70,
        70, 71, 75, 76, 82, 83, 99, 99]])

In [45]:
# values sorted on axis 0
np.sort(df, axis=0)

array([[ 3,  0,  5,  2,  5, 12,  7,  1,  4,  5,  2,  3,  0,  4,  3,  1,
         1, 12,  7,  2,  3,  3,  0,  8],
       [ 4,  2,  7,  9,  7, 16, 19, 19,  9,  9,  4, 10,  2, 11, 11,  7,
         1, 13, 13,  5,  5,  5, 10, 11],
       [ 5,  2, 10, 14, 13, 16, 28, 23, 10,  9, 10, 12, 13, 17, 11, 11,
         1, 18, 21,  6, 20,  7, 13, 12],
       [22,  2, 11, 17, 19, 24, 28, 27, 13, 12, 17, 12, 17, 23, 13, 14,
         2, 20, 22, 18, 23, 11, 15, 12],
       [28,  5, 13, 23, 24, 26, 29, 28, 14, 13, 26, 14, 20, 23, 19, 25,
         3, 22, 24, 25, 27, 17, 18, 14],
       [36,  6, 14, 36, 24, 29, 29, 39, 19, 17, 26, 15, 21, 24, 20, 29,
         7, 30, 35, 34, 28, 17, 18, 19],
       [37,  8, 19, 37, 32, 31, 33, 42, 20, 25, 27, 18, 24, 33, 23, 44,
         8, 31, 37, 36, 31, 20, 21, 23],
       [40, 31, 21, 43, 43, 36, 39, 44, 22, 34, 27, 20, 26, 35, 26, 44,
        10, 34, 53, 37, 33, 31, 21, 27],
       [42, 33, 33, 43, 51, 38, 42, 52, 27, 38, 31, 22, 29, 38, 27, 48,
        14, 43, 53, 40, 35, 33, 22, 30],
       [42, 33, 43, 51, 55, 39, 44, 54, 31, 48, 45, 29, 33, 39, 28, 59,
        22, 46, 54, 44, 38, 33, 25, 31],
       [44, 37, 45, 52, 60, 42, 46, 56, 41, 66, 49, 30, 37, 48, 29, 60,
        26, 52, 60, 44, 40, 38, 27, 35],
       [45, 44, 46, 54, 68, 45, 46, 58, 49, 70, 50, 30, 43, 51, 29, 63,
        33, 53, 61, 48, 41, 42, 28, 41],
       [51, 46, 46, 57, 68, 49, 54, 62, 55, 71, 55, 40, 51, 57, 30, 63,
        36, 59, 65, 50, 42, 49, 32, 41],
       [51, 47, 50, 57, 69, 51, 58, 64, 58, 72, 57, 47, 52, 68, 34, 64,
        48, 61, 69, 55, 44, 50, 37, 50],
       [52, 47, 51, 59, 74, 52, 60, 65, 62, 76, 63, 59, 56, 71, 38, 65,
        60, 73, 69, 56, 46, 51, 37, 54],
       [66, 52, 57, 64, 74, 56, 64, 65, 64, 77, 70, 65, 61, 72, 42, 67,
        64, 73, 72, 62, 46, 51, 45, 56],
       [71, 55, 74, 66, 74, 65, 66, 66, 66, 77, 74, 69, 62, 73, 42, 74,
        66, 74, 75, 63, 58, 53, 46, 56],
       [80, 63, 74, 68, 75, 67, 69, 67, 67, 82, 74, 79, 69, 79, 42, 76,
        78, 76, 78, 65, 62, 62, 49, 59],
       [83, 66, 75, 69, 84, 71, 70, 68, 68, 82, 76, 84, 70, 86, 48, 81,
        79, 77, 80, 69, 64, 78, 63, 62],
       [85, 74, 75, 83, 84, 76, 72, 73, 74, 90, 79, 84, 71, 87, 59, 82,
        89, 80, 80, 71, 82, 80, 68, 68],
       [91, 80, 80, 83, 86, 86, 81, 75, 79, 93, 81, 87, 71, 88, 68, 83,
        90, 90, 81, 72, 86, 91, 71, 70],
       [92, 82, 82, 89, 86, 87, 84, 91, 87, 94, 83, 97, 85, 89, 71, 83,
        91, 90, 83, 84, 92, 94, 75, 71],
       [94, 85, 89, 91, 93, 97, 86, 92, 94, 95, 87, 98, 93, 92, 73, 85,
        94, 94, 91, 92, 95, 94, 86, 79],
       [94, 99, 98, 97, 96, 99, 89, 95, 94, 96, 98, 99, 98, 98, 99, 89,
        98, 99, 92, 92, 97, 99, 92, 87]])

In [46]:
# indices of values in sorted list
np.argsort(dataset)

array([[6, 3, 7, 4, 5, 0, 8, 1, 2],
       [0, 5, 4, 8, 1, 3, 2, 7, 6],
       [2, 1, 0, 6, 4, 5, 7, 8, 3],
       [0, 5, 7, 2, 1, 8, 4, 6, 3],
       [4, 7, 8, 2, 6, 0, 1, 3, 5],
       [4, 2, 5, 3, 8, 1, 7, 0, 6],
       [6, 5, 2, 8, 3, 1, 4, 0, 7],
       [8, 7, 0, 6, 5, 3, 4, 1, 2],
       [1, 8, 5, 6, 4, 2, 3, 0, 7],
       [4, 1, 6, 3, 8, 2, 5, 7, 0],
       [8, 7, 6, 5, 1, 3, 0, 4, 2],
       [4, 3, 0, 7, 2, 5, 6, 8, 1],
       [4, 6, 5, 0, 8, 7, 3, 2, 1],
       [1, 3, 8, 6, 2, 7, 0, 4, 5],
       [2, 5, 3, 4, 6, 0, 7, 8, 1],
       [1, 2, 3, 5, 6, 7, 8, 4, 0],
       [0, 8, 6, 1, 2, 7, 4, 5, 3],
       [5, 6, 3, 2, 0, 4, 1, 7, 8],
       [6, 5, 1, 0, 7, 8, 3, 2, 4],
       [8, 1, 0, 6, 4, 3, 2, 5, 7],
       [8, 7, 4, 2, 5, 6, 1, 0, 3],
       [7, 8, 0, 5, 4, 6, 1, 2, 3],
       [1, 5, 0, 6, 4, 2, 8, 7, 3],
       [4, 0, 3, 5, 1, 7, 2, 6, 8]], dtype=int64)