# Activity 1.01: Using NumPy to compute the *mean*, *median*, *variance*, and *standard deviation* of a dataset

In [1]:
import numpy as np

In [2]:
dataset = np.genfromtxt('../Datasets/normal_distribution.csv', delimiter=',')

In [3]:
# Print a subset of the first two rows of the dataset
print(dataset[0:2,:])

[[ 99.14931546 104.03852715 107.43534677  97.85230675  98.74986914
   98.80833412  96.81964892  98.56783189]
 [ 92.02628776  97.10439252  99.32066924  97.24584816  92.9267508
   92.65657752 105.7197853  101.23162942]]

In [4]:
# The mean of the third row
np.mean(dataset[2])

100.20466135250001

In [5]:
# Index the last element of an ndarray
dataset[-1,-1]

100.07721494

In [6]:
# Get a submatrix of the first three elements of every row of the first three column
dataset[0:3, 0:3]

array([[ 99.14931546, 104.03852715, 107.43534677],
       [ 92.02628776,  97.10439252,  99.32066924],
       [ 95.66253664,  95.17750125,  90.93318132]])

In [7]:
np.median(dataset[-1,:])

99.18748092

In [8]:
dataset[:, -3:]

array([[ 98.80833412,  96.81964892,  98.56783189],
       [ 92.65657752, 105.7197853 , 101.23162942],
       [105.95297652,  98.37481387, 106.54654286],
       [ 91.6604946 , 106.1472841 ,  95.08715803],
       [108.57980357, 100.79478953,  94.20019732],
       [ 96.2832753 , 104.60344836, 101.13442416],
       [ 95.46493436,  94.35373179, 106.83273763],
       [ 98.74767493,  97.57544275,  92.5748759 ],
       [100.85447132, 101.2226037 , 106.03868807],
       [101.72074646,  96.96851209, 103.29147111],
       [ 99.35999981,  98.87007532,  95.85284217],
       [102.62384733, 105.07475277,  97.59572169],
       [ 95.19184343,  91.32093303, 102.35313953],
       [108.09423367,  96.50342927,  99.58664719],
       [ 99.69982772, 103.05289628, 103.93383957],
       [ 96.34622848,  96.89244283,  98.07122664],
       [105.37011896,  99.07551254, 104.15899829],
       [ 98.65912661,  98.72774132, 104.70526438],
       [ 96.5937781 ,  93.04610867,  99.92159953],
       [101.83845792,  97.94046856, 102.20618501],
       [103.40412146, 106.38276709,  98.00253006],
       [ 99.99579473, 101.32113654,  94.76253572],
       [ 95.62359311,  97.99762409, 103.83852459],
       [ 98.75108352, 106.05042487, 100.07721494]])

In [9]:
np.median(dataset, axis=1)

array([ 98.77910163,  97.17512034,  98.58782879, 100.68449836,
       101.00170737,  97.76908825, 101.85002253, 100.04756697,
       102.24292555,  99.59514997, 100.4955753 ,  99.8860714 ,
        99.00647994,  98.67276177, 102.44376222,  96.61933565,
       104.0968893 , 100.72023043,  98.70877396,  99.75008654,
       104.89344428, 101.00634942,  98.30543801,  99.18748092])

In [10]:
np.var(dataset, axis=0)

array([23.64757465, 29.78886109, 20.50542011, 26.03204443, 28.38853175,
       19.09960817, 17.67291174, 16.17923204])

In [11]:
np.var(dataset[-2:,:2])

4.674691991769191

In [12]:
np.std(dataset)

4.838197554269257

In [13]:
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.74767493,  97.57544275,  92.5748759 ],
       [105.30350449,  92.87730812, 103.19258339, 104.40518318,
        101.29326772, 100.85447132, 101.2226037 , 106.03868807],
       [110.44484313,  93.87155456, 101.5363647 ,  97.65393524,
         92.75048583, 101.72074646,  96.96851209, 103.29147111],
       [101.3514185 , 100.37372248, 106.6471081 , 100.61742813,
        105.0320535 ,  99.35999981,  98.87007532,  95.85284217],
       [ 97.21315663, 107.02874163, 102.17642112,  96.74630281,
         95.93799169, 102.62384733, 105.07475277,  97.59572169],
       [ 95.65982034, 107.22482426, 107.19119932, 102.93039474,
         85.98839623,  95.19184343,  91.32093303, 102.35313953],
       [100.39303522,  92.0108226 ,  97.75887636,  93.18884302,
        100.44940274, 108.09423367,  96.50342927,  99.58664719],
       [103.1521596 , 109.40523174,  93.83969256,  99.95827854,
        101.83462816,  99.69982772, 103.05289628, 103.93383957],
       [106.11454989,  88.80221141,  94.5081787 ,  94.59300658,
        101.08830521,  96.34622848,  96.89244283,  98.07122664],
       [ 96.78266211,  99.84251605, 104.03478031, 106.57052697,
        105.13668343, 105.37011896,  99.07551254, 104.15899829],
       [101.86186193, 103.61720152,  99.57859892,  99.4889538 ,
        103.05541444,  98.65912661,  98.72774132, 104.70526438],
       [ 97.49594839,  96.59385486, 104.63817694, 102.55198606,
        105.86078488,  96.5937781 ,  93.04610867,  99.92159953],
       [ 96.76814836,  91.6779221 , 101.79132774, 101.20773355,
         98.29243952, 101.83845792,  97.94046856, 102.20618501],
       [106.89005002, 106.57364584, 102.26648279, 107.40064604,
         99.94318168, 103.40412146, 106.38276709,  98.00253006],
       [ 99.80873105, 101.63973121, 106.46476468, 110.43976681,
        100.69156231,  99.99579473, 101.32113654,  94.76253572],
       [ 96.10020311,  94.57421727, 100.80409326, 105.02389857,
         98.61325194,  95.62359311,  97.99762409, 103.83852459],
       [ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
         93.97853495,  98.75108352, 106.05042487, 100.07721494]])

In [14]:
# index single element in outermost dimension, first row
dataset[0]

array([ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
        98.74986914,  98.80833412,  96.81964892,  98.56783189])

In [15]:
dataset[0,:]

array([ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
        98.74986914,  98.80833412,  96.81964892,  98.56783189])

In [16]:
# index in reversed order in outermost dimension 
dataset[-1]

array([ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
        93.97853495,  98.75108352, 106.05042487, 100.07721494])

In [17]:
dataset[-1,:]

array([ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
        93.97853495,  98.75108352, 106.05042487, 100.07721494])

In [19]:
# index single element in two-dimensional data 
dataset[1,1]

97.10439252

In [20]:
# index in reversed order in two-dimensional data, the last element in the matrix
dataset[-1,-1]

100.07721494

In [21]:
# rows 1 and 2
dataset[1:3]

array([[ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286]])

In [22]:
# 2x2 subset of the data
dataset[:2,:2]

array([[ 99.14931546, 104.03852715],
       [ 92.02628776,  97.10439252]])

In [23]:
# last row with elements reversed
dataset[-1, ::-1]

array([100.07721494, 106.05042487,  98.75108352,  93.97853495,
        97.62787811, 104.51786419,  99.62387832,  94.11176915])

In [25]:
dataset[-1, :]

array([ 94.11176915,  99.62387832, 104.51786419,  97.62787811,
        93.97853495,  98.75108352, 106.05042487, 100.07721494])

In [26]:
# last 4 rows, every other element up to index 6
dataset[-5:-1,:6:2]

array([[ 96.76814836, 101.79132774,  98.29243952],
       [106.89005002, 102.26648279,  99.94318168],
       [ 99.80873105, 106.46476468, 100.69156231],
       [ 96.10020311, 100.80409326,  98.61325194]])

In [34]:
# create a dataset that fits the data
import pandas as pd
df = pd.DataFrame(np.random.randint(0, 100, size=(24, 24)), columns=list('ABCDEFGHIJKLMNOPQRSTWXYZ'))

In [35]:
df.head()

,A,B,C,D,E,F,G,H,I,J,...,O,P,Q,R,S,T,W,X,Y,Z
0,88,80,38,41,35,5,14,55,21,19,...,50,76,22,24,70,92,6,33,37,66
1,47,49,93,45,73,64,38,98,21,56,...,52,87,1,48,98,92,65,63,4,57
2,7,88,40,30,92,68,98,34,0,0,...,63,57,14,35,2,57,1,35,9,53
3,3,70,20,46,56,65,93,40,82,54,...,99,89,6,69,62,88,34,92,17,14
4,80,48,5,65,83,13,15,78,96,18,...,96,80,73,36,54,53,27,22,43,16

In [36]:
np.hsplit(df, (3))

C:\Users\lorra\anaconda3\envs\dv_workshop\Lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

[     A   B   C   D   E   F   G   H
 0   88  80  38  41  35   5  14  55
 1   47  49  93  45  73  64  38  98
 2    7  88  40  30  92  68  98  34
 3    3  70  20  46  56  65  93  40
 4   80  48   5  65  83  13  15  78
 5   96  30  95  39  61  13  48  72
 6    7  27  91  18   5  57  44  67
 7   68  30  75  50  67  18   3  65
 8   19  60  27  48  90   4  35   4
 9    5  68  79  88  45  85  81  57
 10  21  95  57  44  75  92  70  43
 11  60  97  43  59  74  29  84  89
 12  84  48  59  77  31  67  26  46
 13  93  98   7  78  42  20  44  89
 14  10  19  82  97  84  16   0  82
 15  93  79  45  17  39  13  86  38
 16  19  77  62  27  97  19  68  49
 17  10  67  55  57  29  42  70  92
 18  38  70   0  80  84  44  80  66
 19  99  95   1  89  49  75  51  45
 20  48  17  44   7  88  37  18  58
 21   8   8  70  41  38  35  37  12
 22  80  79  26  68  10  65  25   0
 23  77   5  57  36  59  24  74  18,
      I   J   K   L   M   N   O   P
 0   21  19  73  88   2  66  50  76
 1   21  56  61  51  51  99  52  87
 2    0   0  92  15  88  11  63  57
 3   82  54  12  97   9  30  99  89
 4   96  18   4  43  81  72  96  80
 5   46  51  39  28  21  11  78   6
 6   74  53  47  90  82   9  28  78
 7   15  91   9  77  18  37  30  74
 8    9  51  93  97  72  68  89  84
 9   49  39   3  33  69  35  48  47
 10  23  95  94  58  45   4  76  38
 11  63  49  48  20  45  32  85  18
 12  41  37  13   2  55  94  34  77
 13  86  40  37  56  16  12  22  56
 14  34  94   5  56  98  95  20  58
 15  22  33  52  49   5  97  12  71
 16  56  38  94  94   5  58  23  63
 17  53  46  75  32  60  71  88  38
 18  44  14   4  35  81  78  68  24
 19  44  74  69  37  75  88  94  74
 20  39  18  26  84   5  92  52  72
 21  96  20  89  31  30  44  78  64
 22   6   5  22  35  68  21  49  16
 23  76  14  16  25  43  11  75  75,
      Q   R   S   T   W   X   Y   Z
 0   22  24  70  92   6  33  37  66
 1    1  48  98  92  65  63   4  57
 2   14  35   2  57   1  35   9  53
 3    6  69  62  88  34  92  17  14
 4   73  36  54  53  27  22  43  16
 5   21  10  29  88  95  60  97  87
 6   68  70  52  46  30  63  84   3
 7    9  67   8  72  95  19  74   3
 8   45  46  62  67  35  60  86  69
 9   29  50  40  22  93   8  35  43
 10  52  57  68  68  50   8  17  63
 11  83  28   9  38  89  24  52  75
 12  38   9   9  57  15   4  66  53
 13  70  95  94  54  92   9  18  93
 14  57  10  63  32  94  66  27  44
 15  11  83  23  78   4  39  57   1
 16  35  25  42  40  28  42  15  76
 17  74  35  71  57  38   6  25  61
 18  18  61  39  44  30  66  31   8
 19  16  46  67  99  47  82  84   0
 20  13  40  44  34  74  39  54   4
 21  15  74  15  85  63  56  88  31
 22  18  31  68   0  54  11  72  85
 23  33  99   4  41  14   1   4  83]

In [38]:
# split vertically in 2 equal lists
np.vsplit(df,(2))

C:\Users\lorra\anaconda3\envs\dv_workshop\Lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

[     A   B   C   D   E   F   G   H   I   J  ...   O   P   Q   R   S   T   W  \
 0   88  80  38  41  35   5  14  55  21  19  ...  50  76  22  24  70  92   6
 1   47  49  93  45  73  64  38  98  21  56  ...  52  87   1  48  98  92  65
 2    7  88  40  30  92  68  98  34   0   0  ...  63  57  14  35   2  57   1
 3    3  70  20  46  56  65  93  40  82  54  ...  99  89   6  69  62  88  34
 4   80  48   5  65  83  13  15  78  96  18  ...  96  80  73  36  54  53  27
 5   96  30  95  39  61  13  48  72  46  51  ...  78   6  21  10  29  88  95
 6    7  27  91  18   5  57  44  67  74  53  ...  28  78  68  70  52  46  30
 7   68  30  75  50  67  18   3  65  15  91  ...  30  74   9  67   8  72  95
 8   19  60  27  48  90   4  35   4   9  51  ...  89  84  45  46  62  67  35
 9    5  68  79  88  45  85  81  57  49  39  ...  48  47  29  50  40  22  93
 10  21  95  57  44  75  92  70  43  23  95  ...  76  38  52  57  68  68  50
 11  60  97  43  59  74  29  84  89  63  49  ...  85  18  83  28   9  38  89

      X   Y   Z
 0   33  37  66
 1   63   4  57
 2   35   9  53
 3   92  17  14
 4   22  43  16
 5   60  97  87
 6   63  84   3
 7   19  74   3
 8   60  86  69
 9    8  35  43
 10   8  17  63
 11  24  52  75

 [12 rows x 24 columns],
      A   B   C   D   E   F   G   H   I   J  ...   O   P   Q   R   S   T   W  \
 12  84  48  59  77  31  67  26  46  41  37  ...  34  77  38   9   9  57  15
 13  93  98   7  78  42  20  44  89  86  40  ...  22  56  70  95  94  54  92
 14  10  19  82  97  84  16   0  82  34  94  ...  20  58  57  10  63  32  94
 15  93  79  45  17  39  13  86  38  22  33  ...  12  71  11  83  23  78   4
 16  19  77  62  27  97  19  68  49  56  38  ...  23  63  35  25  42  40  28
 17  10  67  55  57  29  42  70  92  53  46  ...  88  38  74  35  71  57  38
 18  38  70   0  80  84  44  80  66  44  14  ...  68  24  18  61  39  44  30
 19  99  95   1  89  49  75  51  45  44  74  ...  94  74  16  46  67  99  47
 20  48  17  44   7  88  37  18  58  39  18  ...  52  72  13  40  44  34  74
 21   8   8  70  41  38  35  37  12  96  20  ...  78  64  15  74  15  85  63
 22  80  79  26  68  10  65  25   0   6   5  ...  49  16  18  31  68   0  54
 23  77   5  57  36  59  24  74  18  76  14  ...  75  75  33  99   4  41  14

      X   Y   Z
 12   4  66  53
 13   9  18  93
 14  66  27  44
 15  39  57   1
 16  42  15  76
 17   6  25  61
 18  66  31   8
 19  82  84   0
 20  39  54   4
 21  56  88  31
 22  11  72  85
 23   1   4  83

 [12 rows x 24 columns]]

In [42]:
# iterating over whole dataset (each value in each row)
for x in np.nditer(dataset):
    print(x)

99.14931546
104.03852715
107.43534677
97.85230675
98.74986914
98.80833412
96.81964892
98.56783189
92.02628776
97.10439252
99.32066924
97.24584816
92.9267508
92.65657752
105.7197853
101.23162942
95.66253664
95.17750125
90.93318132
110.18889465
98.80084371
105.95297652
98.37481387
106.54654286
91.37294597
100.96781394
100.40118279
113.42090475
105.48508838
91.6604946
106.1472841
95.08715803
101.20862522
103.5730309
100.28690912
105.85269352
93.37126331
108.57980357
100.79478953
94.20019732
102.80387079
98.29687616
93.24376389
97.24130034
89.03452725
96.2832753
104.60344836
101.13442416
106.71751618
102.97585605
98.45723272
100.72418901
106.39798503
95.46493436
94.35373179
106.83273763
96.02548256
102.82360856
106.47551845
101.34745901
102.45651798
98.74767493
97.57544275
92.5748759
105.30350449
92.87730812
103.19258339
104.40518318
101.29326772
100.85447132
101.2226037
106.03868807
110.44484313
93.87155456
101.5363647
97.65393524
92.75048583
101.72074646
96.96851209
103.29147111
101.3514185
100.37372248
106.6471081
100.61742813
105.0320535
99.35999981
98.87007532
95.85284217
97.21315663
107.02874163
102.17642112
96.74630281
95.93799169
102.62384733
105.07475277
97.59572169
95.65982034
107.22482426
107.19119932
102.93039474
85.98839623
95.19184343
91.32093303
102.35313953
100.39303522
92.0108226
97.75887636
93.18884302
100.44940274
108.09423367
96.50342927
99.58664719
103.1521596
109.40523174
93.83969256
99.95827854
101.83462816
99.69982772
103.05289628
103.93383957
106.11454989
88.80221141
94.5081787
94.59300658
101.08830521
96.34622848
96.89244283
98.07122664
96.78266211
99.84251605
104.03478031
106.57052697
105.13668343
105.37011896
99.07551254
104.15899829
101.86186193
103.61720152
99.57859892
99.4889538
103.05541444
98.65912661
98.72774132
104.70526438
97.49594839
96.59385486
104.63817694
102.55198606
105.86078488
96.5937781
93.04610867
99.92159953
96.76814836
91.6779221
101.79132774
101.20773355
98.29243952
101.83845792
97.94046856
102.20618501
106.89005002
106.57364584
102.26648279
107.40064604
99.94318168
103.40412146
106.38276709
98.00253006
99.80873105
101.63973121
106.46476468
110.43976681
100.69156231
99.99579473
101.32113654
94.76253572
96.10020311
94.57421727
100.80409326
105.02389857
98.61325194
95.62359311
97.99762409
103.83852459
94.11176915
99.62387832
104.51786419
97.62787811
93.97853495
98.75108352
106.05042487
100.07721494

In [43]:
"""
iterating over the whole dataset with indices matching the position in the dataset
"""
for index, value in np.ndenumerate(dataset):
    print(index, value)

(0, 0) 99.14931546
(0, 1) 104.03852715
(0, 2) 107.43534677
(0, 3) 97.85230675
(0, 4) 98.74986914
(0, 5) 98.80833412
(0, 6) 96.81964892
(0, 7) 98.56783189
(1, 0) 92.02628776
(1, 1) 97.10439252
(1, 2) 99.32066924
(1, 3) 97.24584816
(1, 4) 92.9267508
(1, 5) 92.65657752
(1, 6) 105.7197853
(1, 7) 101.23162942
(2, 0) 95.66253664
(2, 1) 95.17750125
(2, 2) 90.93318132
(2, 3) 110.18889465
(2, 4) 98.80084371
(2, 5) 105.95297652
(2, 6) 98.37481387
(2, 7) 106.54654286
(3, 0) 91.37294597
(3, 1) 100.96781394
(3, 2) 100.40118279
(3, 3) 113.42090475
(3, 4) 105.48508838
(3, 5) 91.6604946
(3, 6) 106.1472841
(3, 7) 95.08715803
(4, 0) 101.20862522
(4, 1) 103.5730309
(4, 2) 100.28690912
(4, 3) 105.85269352
(4, 4) 93.37126331
(4, 5) 108.57980357
(4, 6) 100.79478953
(4, 7) 94.20019732
(5, 0) 102.80387079
(5, 1) 98.29687616
(5, 2) 93.24376389
(5, 3) 97.24130034
(5, 4) 89.03452725
(5, 5) 96.2832753
(5, 6) 104.60344836
(5, 7) 101.13442416
(6, 0) 106.71751618
(6, 1) 102.97585605
(6, 2) 98.45723272
(6, 3) 100.72418901
(6, 4) 106.39798503
(6, 5) 95.46493436
(6, 6) 94.35373179
(6, 7) 106.83273763
(7, 0) 96.02548256
(7, 1) 102.82360856
(7, 2) 106.47551845
(7, 3) 101.34745901
(7, 4) 102.45651798
(7, 5) 98.74767493
(7, 6) 97.57544275
(7, 7) 92.5748759
(8, 0) 105.30350449
(8, 1) 92.87730812
(8, 2) 103.19258339
(8, 3) 104.40518318
(8, 4) 101.29326772
(8, 5) 100.85447132
(8, 6) 101.2226037
(8, 7) 106.03868807
(9, 0) 110.44484313
(9, 1) 93.87155456
(9, 2) 101.5363647
(9, 3) 97.65393524
(9, 4) 92.75048583
(9, 5) 101.72074646
(9, 6) 96.96851209
(9, 7) 103.29147111
(10, 0) 101.3514185
(10, 1) 100.37372248
(10, 2) 106.6471081
(10, 3) 100.61742813
(10, 4) 105.0320535
(10, 5) 99.35999981
(10, 6) 98.87007532
(10, 7) 95.85284217
(11, 0) 97.21315663
(11, 1) 107.02874163
(11, 2) 102.17642112
(11, 3) 96.74630281
(11, 4) 95.93799169
(11, 5) 102.62384733
(11, 6) 105.07475277
(11, 7) 97.59572169
(12, 0) 95.65982034
(12, 1) 107.22482426
(12, 2) 107.19119932
(12, 3) 102.93039474
(12, 4) 85.98839623
(12, 5) 95.19184343
(12, 6) 91.32093303
(12, 7) 102.35313953
(13, 0) 100.39303522
(13, 1) 92.0108226
(13, 2) 97.75887636
(13, 3) 93.18884302
(13, 4) 100.44940274
(13, 5) 108.09423367
(13, 6) 96.50342927
(13, 7) 99.58664719
(14, 0) 103.1521596
(14, 1) 109.40523174
(14, 2) 93.83969256
(14, 3) 99.95827854
(14, 4) 101.83462816
(14, 5) 99.69982772
(14, 6) 103.05289628
(14, 7) 103.93383957
(15, 0) 106.11454989
(15, 1) 88.80221141
(15, 2) 94.5081787
(15, 3) 94.59300658
(15, 4) 101.08830521
(15, 5) 96.34622848
(15, 6) 96.89244283
(15, 7) 98.07122664
(16, 0) 96.78266211
(16, 1) 99.84251605
(16, 2) 104.03478031
(16, 3) 106.57052697
(16, 4) 105.13668343
(16, 5) 105.37011896
(16, 6) 99.07551254
(16, 7) 104.15899829
(17, 0) 101.86186193
(17, 1) 103.61720152
(17, 2) 99.57859892
(17, 3) 99.4889538
(17, 4) 103.05541444
(17, 5) 98.65912661
(17, 6) 98.72774132
(17, 7) 104.70526438
(18, 0) 97.49594839
(18, 1) 96.59385486
(18, 2) 104.63817694
(18, 3) 102.55198606
(18, 4) 105.86078488
(18, 5) 96.5937781
(18, 6) 93.04610867
(18, 7) 99.92159953
(19, 0) 96.76814836
(19, 1) 91.6779221
(19, 2) 101.79132774
(19, 3) 101.20773355
(19, 4) 98.29243952
(19, 5) 101.83845792
(19, 6) 97.94046856
(19, 7) 102.20618501
(20, 0) 106.89005002
(20, 1) 106.57364584
(20, 2) 102.26648279
(20, 3) 107.40064604
(20, 4) 99.94318168
(20, 5) 103.40412146
(20, 6) 106.38276709
(20, 7) 98.00253006
(21, 0) 99.80873105
(21, 1) 101.63973121
(21, 2) 106.46476468
(21, 3) 110.43976681
(21, 4) 100.69156231
(21, 5) 99.99579473
(21, 6) 101.32113654
(21, 7) 94.76253572
(22, 0) 96.10020311
(22, 1) 94.57421727
(22, 2) 100.80409326
(22, 3) 105.02389857
(22, 4) 98.61325194
(22, 5) 95.62359311
(22, 6) 97.99762409
(22, 7) 103.83852459
(23, 0) 94.11176915
(23, 1) 99.62387832
(23, 2) 104.51786419
(23, 3) 97.62787811
(23, 4) 93.97853495
(23, 5) 98.75108352
(23, 6) 106.05042487
(23, 7) 100.07721494